#Default port is 8763
server:
  port: 8763
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
    level:
        com.crotontech: DEBUG
spring:
  profiles:
    include: microservices-security
sample:
  webservices:
    registration: registrationservice
