#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.crotontech: DEBUG

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8764


spring:
  application:
    name: authservice
  profiles:
    include: microservices-security
  datasource:
    url: jdbc:mysql://localhost:3306/remedial
    username: root
    password: R00tp@ss!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

microservices-security:
    jwt:
        login-url: /login
        refresh-token-url: /refreshtoken
        header: Authorization
        prefix: Bearer
        expiration: 86400
        secret: 1d655ec8-b0cb-47b0-b4bf-1b3a2fe649a6


